### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [rszalski/erfc#8]
https://pypi.org/project/erfc/ = 404 ;-(  Reserve it before someone else does :P  Also distro packaging processes typically require PyPI releases and the PyPI name is used for their package naming conventions.

**Comment by rszalski** [comment]
@jayvdb Thank you for highlighting this and motivating me :) The release is done https://github.com/rszalski/erfc/releases/tag/v0.1.0 and available on PyPi!
